// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXT4DHgTIxH-xZ3sttAGRmcRBhzzJU9wM',
    appId: '1:771533699007:web:1dcb9ccb29ea14002e130a',
    messagingSenderId: '771533699007',
    projectId: 'yes-tracker',
    authDomain: 'yes-tracker.firebaseapp.com',
    storageBucket: 'yes-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFw7BuIFS8PuNNOs0-SL_B9w8Q0vcp5vM',
    appId: '1:771533699007:android:fdec816877fbe4652e130a',
    messagingSenderId: '771533699007',
    projectId: 'yes-tracker',
    storageBucket: 'yes-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ8LpvK3i7S_QC9YZp4OxRzqNoyZ4uGG0',
    appId: '1:771533699007:ios:cbcb1b2057d5a6a82e130a',
    messagingSenderId: '771533699007',
    projectId: 'yes-tracker',
    storageBucket: 'yes-tracker.appspot.com',
    iosBundleId: 'com.yestracker.driversapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ8LpvK3i7S_QC9YZp4OxRzqNoyZ4uGG0',
    appId: '1:771533699007:ios:3e0404469e901dd82e130a',
    messagingSenderId: '771533699007',
    projectId: 'yes-tracker',
    storageBucket: 'yes-tracker.appspot.com',
    iosBundleId: 'com.yestracker.driversapp.RunnerTests',
  );
}
